### ISSUE TITLE
Error while running any install command

### ISSUE THREAD

**Issue by ragasubekti** [ayasa520/waydroid_script#2]
System Info:
OS: Arch Linux x86_64
CPU: Intel Core i9-12900K
GPU: Intel

Currently running any install command on Arch system will return error. This doesn't happen in original `casualsnek` version.

```
INFO: Downloading libhoudini.zip now to /home/noir/.cache/waydroid-script/downloads/libhoudini.zip .....
98.6MiB [00:16, 5.81MiB/s]
INFO: Extracting archive...
INFO: Resizing /var/lib/waydroid/images/system.img to 2157M
Traceback (most recent call last):
  File "/home/noir/Projects/waydroid_script/main.py", line 116, in <module>
    main()
  File "/home/noir/Projects/waydroid_script/main.py", line 109, in main
    args.func(*args.app)
  File "/home/noir/Projects/waydroid_script/main.py", line 28, in install
    Houdini().install()
  File "/home/noir/Projects/waydroid_script/stuffs/general.py", line 153, in install
    self.resize()
  File "/home/noir/Projects/waydroid_script/stuffs/general.py", line 99, in resize
    images.resize(img, new_size)
  File "/home/noir/Projects/waydroid_script/tools/images.py", line 27, in resize
    run(["sudo", "e2fsck", "-y", "-f", img_file], "^e2fsck \d+\.\d+\.\d (.+)\n$")
  File "/home/noir/Projects/waydroid_script/tools/helper.py", line 26, in run
    result = subprocess.run(args=args, env=env, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1763, in _execute_child
    for k, v in env.items():
AttributeError: 'str' object has no attribute 'items'
```

**Comment by ayasa520** [comment]
https://github.com/ayasa520/waydroid_script/commit/6c5637fc8f598c94c40ee0a1be3964f6ed9d9078

**Comment by ragasubekti** [comment]
That fixes it, thanks
