### ISSUE TITLE
problems to use script

### ISSUE THREAD

**Issue by RSerejo** [ayasa520/waydroid_script#4]
Using cached aapt2-0.2.1-py3-none-any.whl (5.6 MB)
Installing collected packages: aapt2
Successfully installed aapt2-0.2.1
[serejo@nobara-pc waydroid_script]$ sudo python3 main.py install libndk
Traceback (most recent call last):
  File "/mnt/HD/Downloads/git/New Folder (1)/waydroid_script/main.py", line 10, in <module>
    from stuffs.microg import MicroG
  File "/mnt/HD/Downloads/git/New Folder (1)/waydroid_script/stuffs/microg.py", line 6, in <module>
    from aapt2 import aapt
 

but i have aapt installed

**Comment by ayasa520** [comment]
try `sudo pip install aapt2`

**Comment by RSerejo** [comment]
aapt2 already was installed but now it's working, maybe it was my machine problem.
it to libndk work with Android 11? because for me is not.

**Comment by ayasa520** [comment]
yes it should work

**Comment by ayasa520** [comment]
> aapt2 already was installed but now it's working, maybe it was my machine problem. it to libndk work with Android 11? because for me is not.

any logs?

**Comment by RSerejo** [comment]
> > aapt2 already was installed but now it's working, maybe it was my machine problem. it to libndk work with Android 11? because for me is not.
> 
> any logs?

how can i collect it?

**Comment by ayasa520** [comment]
> how can i collect it?

Run `sudo waydroid shell -- sh -c "logcat -c" && sudo waydroid shell logcat > logfile.txt` , then launch an app. And libndk doesn't make all apps work, can you tell me what app you tested?

**Comment by RSerejo** [comment]
> 

05-17 20:36:41.726    25    25 E lowmemorykiller: Failed to get free memory!
05-17 20:36:41.736    25    25 E lowmemorykiller: /proc/zoneinfo parse error
05-17 20:36:41.736    25    25 E lowmemorykiller: Failed to get free memory!
05-17 20:36:41.746    25    25 E lowmemorykiller: /proc/zoneinfo parse error
05-17 20:36:41.746    25    25 E lowmemorykiller: Failed to get free memory!
05-17 20:36:41.756    25    25 E lowmemorykiller: /proc/zoneinfo parse error
05-17 20:36:41.756    25    25 E lowmemorykiller: Failed to get free memory!
05-17 20:36:41.766    25    25 E lowmemorykiller: /proc/zoneinfo parse error
05-17 20:36:41.767    25    25 E lowmemorykiller: Failed to get free memory!
05-17 20:36:41.777    25    25 E lowmemorykiller: /proc/zoneinfo parse error
05-17 20:36:41.777    25    25 E lowmemorykiller: Failed to get free memory!
05-17 20:36:41.787    25    25 E lowmemorykiller: /proc/zoneinfo parse error
05-17 20:36:41.787    25    25 E lowmemorykiller: Failed to get free memory!
05-17 20:36:41.797    25    25 E lowmemorykiller: /proc/zoneinfo parse error
05-17 20:36:41.797    25    25 E lowmemorykiller: Failed to get free memory!
05-17 20:36:41.807    25    25 E lowmemorykiller: /proc/zoneinfo parse error
05-17 20:36:41.807    25    25 E lowmemorykiller: Failed to get free memory!
05-17 20:36:41.817    25    25 E lowmemorykiller: /proc/zoneinfo parse error
05-17 20:36:41.817    25    25 E lowmemorykiller: Failed to get free memory!
05-17 20:36:41.827    25    25 E lowmemorykiller: /proc/zoneinfo parse error
05-17 20:36:41.827    25    25 E lowmemorykiller: Failed to get free memory!
